name: Send preview to Surge

on:
  push:
    branches:
      - preview

concurrency:
  group: "preview"
  cancel-in-progress: true

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "VITE_HOURLY_RATE=${{ vars.VITE_HOURLY_RATE }}" >> .env

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          npm install -g surge
          cd build
          surge --project . --token ${{ secrets.SURGE_TOKEN }}
